version: "3.5"
services:

    clinfile:
        build: php
        container_name: www_docker_clinfile
        ports:
          - "8665:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
            
                        
                              
networks:
    dev:

volumes:
    db-data:
